# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  #- linux
  - osx
  #- windows
julia:
  #- 1.1 #Long-term support (LTS) release: v1.0.5 (Sep 9, 2019)
  #- 1.2
  #- 1.3
  #- 1.4
  - 1.5
  #- nightly
notifications:
  email: false

#codecov: true
coveralls: true

## uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
# matrix:
#  allow_failures:
#   - julia: nightly
#   - os: windows

jobs:
  allow_failures:
   - julia: nightly
   - os: windows
  include:
    - stage: "Documentation"
      julia: 1.5
      os: osx #linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

after_success:
 - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'


# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Stopping"); Pkg.test("Stopping"; coverage=true)'
# after_success:
#   # push coverage results to Coveralls
#   - julia -e 'cd(Pkg.dir("Stopping")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
#   # push coverage results to Codecov
#   - julia -e 'cd(Pkg.dir("Stopping")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
